name: Code scanning

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codeql:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CodeQL
        uses: github/codeql-action/setup-python@v1
        with:
          python-version: '3.x'

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v1
        with:
          category: 'Security'
